name: sync wiki

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://decathlon/wiki-page-creator-action:2.0.0
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          ACTION_MAIL: bot@radiome-lab.org
          ACTION_NAME: Radiome Bot
          OWNER: radiome-lab
          REPO_NAME: radiome
          MD_FOLDER: docs
